services:
    php:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - ./:/srv/app
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "MEMCACHED_HOST=localhost"
        depends_on:
          - mysql
    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - mysqldata:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=homestead"
            - "MYSQL_USER=homestead"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_ROOT_PASSWORD=secret"
    memcached:
        image: memcached:latest
        ports:
            - "11211:11211"
volumes:
    mysqldata:

